version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/PangolinGo"
    schedule:
      interval: "daily"
    groups:
      patch-updates:
        update-types:
          - "patch"
      dminor-updates:
        update-types:
          - "minor"